# 00_load_workspace.R

library(tigris)
library(sf)
library(ggplot2)
library(data.table)
library(collapse)
library(modelsummary)
library(readxl)
library(fixest)
library(haven)
library(janitor)
library(dplyr)
library(lehdr)
library(bit64)
library(ivreg)
library(censusapi)
library(tidycensus)
library(sandwich)
library(patchwork)
library(lmtest)